
canonifyurls =  "true"
languageCode = "en-us"

title = "Strata"
theme = "hugo-strata-theme"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "赵智祎"
	description = "太阳的个人网站"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add custom assets with their paths relative to the static folder
	custom_js   = ["./static/js/"]
	custom_css  = ["./static/css/"]


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**I'm the Sun**, 一个业余诗人,To being a coder，现在就读于南京信息工程大学."
		# The icons will be shown if you enter your username
		
		github = "dhzzy88"
	

		copyright = [
			"&copy; 赵智祎____禁止爬虫爬取信息_____欢迎分享和转载，转载请注明来源 RRS:本站支持订阅"
                  ]


	[params.about]
		hide  = false
		title = "他曾是海子的追随者，又把顾城作为自己的膜拜者，然而他们却在历史中慢慢逝去了。他一直迷惘着，一直低落沉默，最憧憬的生活是一边写诗，一边做代码民工，最好能多一些旅行"
		content = "我曾经一直以为自己是一个孤独的人，没有什么人愿意做我的朋友，也没有人会爱我。可是随着时间的推移，身边的朋友和远方的挚友都让我感受到了他们对我的情感，我很愿意作为一个倾听者继续以一个好的角色在你们的生活里，我大多数的时候都愿意沉默，我会改变，但是生活本身的价值并不在此，我可能会随着学生时代的结束，失去自己的一些期望的方向，但是觉得那些并不是错误的事情，恰恰相反这是一个开始，从前一直会幻想很多，把自己放在自己的自由城里，未来要经历很多你要知道生活里有很多比想象地好，也有很多比想象地残酷。每个人都有自己存在的价值，不要伟大，不要天下第一，我仍然会幻想温暖的阳光，照在每一个人的身上，一切都给你"


	[params.portfolio]
		hide  = false
		title = "文章列表"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "这是一张美化博客的图片，来源于主题模版"
			description = "我的博客使用hugo自行搭建，主题模版来源于hugo官网，对此我向开源社区表示感谢"
              


	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "如果你失去了与我的联系，或者想联系我的时候请在下面我的个人联系方式中找到你需要的方式联系我，太阳."

		address = [
			"中国","江苏","南京"
		]
		phone = "15195813018"
                
		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "dhzzy88@163.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 0

[[menu.main]]
	name = "Blog"
	url  = "post/"
	weight = 10

